### ISSUE TITLE
Switchover with slave lag breaks replication

### ISSUE THREAD

**Issue by cpeintre** [tanji/mariadb-tools#8] opened 2015-02-03 13:56 UTC
If all slaves have a replication lag greater than 0, switch over stop with "not in sync" message.

**Comment by tanji** [comment] 2015-02-03 14:07
That's the default behavior in latest version. 

$ ./mariadb-repmgr -help  
Usage of ./mariadb-repmgr:
  -maxdelay=0: Maximum replication delay before initiating failover

Use -maxdelay with the value of your choice.

**Comment by cpeintre** [comment] 2015-02-03 14:09
Sorry, I wasn't clear enough.
The problem occurs even if this parameter is set correctly (greater than 0)

**Comment by tanji** [comment] 2015-02-03 14:13
OK, noted. I'll try to reproduce it.

**Comment by tanji** [comment] 2015-02-03 14:26
OK, I suppose that happens because you use -gtidcheck=true, and that option is misdocumented and misleading (and honestly, should maybe be removed)
If you use that, failover will _never happen_ if slaves have a different Current_GTID position from the master.
However, if you don't use it, and slaves are not beyond maxdelay, the utility will pick up the most up to date slave and will wait for GTID to synchronize before switching.
So to be clear, -gtidcheck=true is not a means to sync the slaves with the master. It's just a hardcore option to make sure that one slave is 100% in sync at switchover time.

**Comment by cpeintre** [comment] 2015-02-03 14:33
Ok, understood. I found the name of this option really comfortable ;-)
Thanks for the explanations.

**Comment by cpeintre** [comment] 2015-02-03 14:36
Now, a switch over with lag on all slaves result with this error on all slaves:
"Got fatal error 1236 from master when reading data from binary log: 'Error: connecting slave requested to start from GTID 1-180533626-14016589, which is not in the master's binlog"

**Comment by tanji** [comment] 2015-02-03 15:43
Issue confirmed.

2015-02-03 15:36 GMT+01:00 Cédric PEINTRE <notifications@github.com>:

> Now, a switch over with lag on all slaves result with this error on all
> slaves:
> "Got fatal error 1236 from master when reading data from binary log:
> 'Error: connecting slave requested to start from GTID 1-180533626-14016589,
> which is not in the master's binlog"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tanji/mariadb-tools/issues/8#issuecomment-72660236>.
>



-- 
Guillaume Lefranc
Dragonscale - Database Consulting
+33682425893

**Comment by tanji** [comment] 2015-02-03 15:44
Issue confirmed.

**Comment by tanji** [comment] 2015-02-04 14:04
The reason for that issue is that switchover may happen before all transactions have completed on demoted master. It causes inconsistency in the replication setup as the new master will be behind some slaves. Looking at that I found other issues, because closing existing transactions is not handled yet. Expect some form of bug fix soon.

**Comment by tanji** [comment] 2015-02-04 16:28
repmgr now correctly handles running threads on demoted master.
There is a configurable killswitch: -wait-kill: number of milliseconds to wait before killing connections on demoted master, if write threads are present. Reads or sleeping connections are killed no matter what.

**Closed as completed by tanji** 2015-02-04 16:28 UTC
